#!/bin/zsh

highs_install="/Users/akbarlatif/installs/highs"
highs_include_dir="$highs_install/include/highs"
highs_lib_dir="$highs_install/lib"

echo $highs_include_dir

# highs_build_dir="${highs_root}/test"; cpp_opt_deb_flag="-O3"
# highs_build_dir="${highs_root}/build"; cpp_opt_deb_flag="-g3"

# g++ ${cpp_opt_deb_flag} -std=c++11 -I "${highs_root}/app/"  -I "${highs_build_dir}" -I "${highs_root}/src/" -L "${highs_build_dir}/lib/" $1 $2 -lhighs

g++ -std=c++11 $1  $2 -I"${highs_include_dir}"  -L"${highs_lib_dir}" -o output -lhighs



